<?php

$title = 'Retirer du panier';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes vous sur de vouloir supprimer
    <?php echo $this->escapeHtml($product->_name); ?>
    de votre panier ?
</p>
<?php
$url = $this->url('cart', array(
    'action' => 'removefromcart',
    'id'     => $this->id,
));
?>
<form action="/cart/removefromcart/<?= $product->_id ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $product->_id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>