<header>
</header>

<main>
    <h1>Votre panier</h1>
    <form action="/paycart" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo (int) $product->_id; ?>" />
            <input type="submit" name="pay" value="Payer" />
        </div>
    </form>
    <table class="datatable">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prix</th>
            <th>Description</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php $total = 0;
        foreach ($products as $a) :
            $total += $a->_price?>
            <tr>
                <td><?= $this->escapeHtml($a->_id) ?></td>
                <td><?= $this->escapeHtml($a->_name) ?></td>
                <td><?= $this->escapeHtml($a->_price) ?></td>
                <td><?= $this->escapeHtml($a->_description) ?></td>
                <td><a class="cursor-ptr" href="<?= $this->url('index',['action'=> 'removefromcart','id' => $a->_id]) ?>">Retirer</a></td>

            </tr>
        <?php endforeach;
            echo '<br/> Prix total HT : ' . $total .'<br/> Prix total avec taxes : ' . ($total + $total * 0.15);
        ?>
        </tbody>
    </table>
</main>